"""Add votes

Revision ID: 9f5a7abbe1fc
Revises: ff5aaf345c27
Create Date: 2023-12-03 15:43:08.479378

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f5a7abbe1fc'
down_revision: Union[str, None] = 'ff5aaf345c27'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('votes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('voter_id', sa.UUID(), nullable=False),
    sa.Column('nominant_id', sa.UUID(), nullable=False),
    sa.Column('nomination_id', sa.UUID(), nullable=False),
    sa.Column('voted_date', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['nominant_id'], ['nominants.id'], ),
    sa.ForeignKeyConstraint(['nomination_id'], ['nominations.id'], ),
    sa.ForeignKeyConstraint(['voter_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('votes')
    # ### end Alembic commands ###
