"""Add user unit

Revision ID: cb64c42e4c95
Revises: cd010d3ef4d7
Create Date: 2023-12-23 22:39:24.482288

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb64c42e4c95'
down_revision: Union[str, None] = 'cd010d3ef4d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'unit',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'unit',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
