"""Add user unit

Revision ID: cd010d3ef4d7
Revises: 9f5a7abbe1fc
Create Date: 2023-12-23 22:35:04.293293

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd010d3ef4d7'
down_revision: Union[str, None] = '9f5a7abbe1fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('unit', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'unit')
    # ### end Alembic commands ###
